#!/usr/bin/env python

import atexit
import os
import readline

xdg_cache_home = os.getenv("XDG_CACHE_HOME", os.path.expanduser("~/.cache"))
history_file = os.path.join(xdg_cache_home, "python_history")

try:
    readline.read_history_file(history_file)
    # default history len is -1 (infinite), which may grow unruly
    readline.set_history_length(1000)
except FileNotFoundError:
    pass

atexit.register(readline.write_history_file, history_file)
