syntax on
set ai si sw=4 ts=4 sts=4 mouse=a
set autochdir
set backspace=indent,eol,start
set clipboard^=unnamed,unnamedplus
set encoding=utf-8
set ignorecase
set incsearch
set mouse+=a
set nocompatible
set noerrorbells visualbell t_vb=
set showcmd
set showmatch
set smartcase
filetype indent on

" XDG support

if empty($MYVIMRC) | let $MYVIMRC = expand('<sfile>:p') | endif

if empty($XDG_CACHE_HOME)  | let $XDG_CACHE_HOME  = $HOME."/.cache"       | endif
if empty($XDG_CONFIG_HOME) | let $XDG_CONFIG_HOME = $HOME."/.config"      | endif
if empty($XDG_DATA_HOME)   | let $XDG_DATA_HOME   = $HOME."/.local/share" | endif

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
silent! call mkdir($XDG_DATA_HOME."/vim/spell", 'p', 0700)
set viewdir=$XDG_DATA_HOME/vim/view | silent! call mkdir(&viewdir, 'p', 0700)

set backupdir=$XDG_CACHE_HOME/vim/backup | silent! call mkdir(&backupdir, 'p', 0700)
set directory=$XDG_CACHE_HOME/vim/swap   | silent! call mkdir(&directory, 'p', 0700)
set undodir=$XDG_CACHE_HOME/vim/undo     | silent! call mkdir(&undodir,   'p', 0700)

if !has('nvim') " Neovim has its own special location
  set viminfo='50,<1000,s100,:0,n$XDG_CACHE_HOME/vim/viminfo
endif

" XDG support ended
