checkForUpdatesAutomatically: true
showFloatingNotifications: true
showMenuBarTitle: false
showMenuBarIcon: true
menuBarTitleTemplate: $WORKSPACE
menuBarDisplayAliases: ''
enableFocusManagement: false
centerCursorOnFocusChange: false
focusFrontmostWindow: false
enableSwipeGestures: true
swipeThreshold: 2e-1
restartAppOnWakeUp: false
swipeLeft3FingerAction: previousWorkspace
swipeRight3FingerAction: nextWorkspace
swipeUp3FingerAction: toggleSpaceControl
swipeDown3FingerAction: hideSpaceControl
swipeLeft4FingerAction: none
swipeRight4FingerAction: none
swipeUp4FingerAction: none
swipeDown4FingerAction: none
displayMode: dynamic
centerCursorOnWorkspaceChange: true
changeWorkspaceOnAppAssign: true
activeWorkspaceOnFocusChange: true
skipEmptyWorkspacesOnSwitch: false
keepUnassignedAppsOnSwitch: false
restoreHiddenAppsOnSwitch: true
enableWorkspaceTransitions: false
workspaceTransitionDuration: 3e-1
workspaceTransitionDimming: 2e-1
loopWorkspaces: true
alternativeDisplays: ''
enablePictureInPictureSupport: true
switchWorkspaceWhenPipCloses: true
pipApps: []
pipScreenCornerOffset: 15
enableSpaceControl: true
enableSpaceControlAnimations: true
enableSpaceControlTilesAnimations: true
spaceControlCurrentDisplayWorkspaces: false
spaceControlHideEmptyWorkspaces: false
spaceControlUpdateScreenshotsOnOpen: false
spaceControlNumberOfColumns: 0
enableIntegrations: true
runScriptOnLaunch: ''
runScriptOnWorkspaceChange: sketchybar --trigger flashspace_workspace_change WORKSPACE="$WORKSPACE"
  DISPLAY="$DISPLAY"
runScriptOnProfileChange: sketchybar --reload
