tap "buo/cask-upgrade"
tap "daviderestivo/emacs-head"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "koekeishiya/formulae"
tap "sunnyyoung/repo"
brew "aspell"
brew "python@3.10"
brew "black"
brew "blueutil"
brew "python@3.9"
brew "glib"
brew "pkg-config"
brew "coreutils"
brew "direnv"
brew "fcitx-remote-for-osx"
brew "fd"
brew "findutils"
brew "gawk"
brew "git"
brew "gnupg"
brew "gnu-sed"
brew "gnu-tar"
brew "grep"
brew "node"
brew "iconsur"
brew "inetutils"
brew "isync"
brew "jq"
brew "jsonnet"
brew "pango"
brew "m-cli"
brew "mackup"
brew "mas"
brew "mermaid-cli"
brew "mist"
brew "moreutils"
brew "mu"
brew "mupdf"
brew "pandoc"
brew "pinentry-mac"
brew "pipx"
brew "pre-commit"
brew "pyright"
brew "ripgrep"
brew "showkey"
brew "starship"
brew "stow"
brew "subversion"
brew "switchaudio-osx"
brew "tealdeer"
brew "terminal-notifier"
brew "tesseract"
brew "tesseract-lang"
brew "texlab"
brew "trash"
brew "tree"
brew "vim"
brew "wakatime-cli"
brew "zoxide"
brew "daviderestivo/emacs-head/emacs-head@28", args: ["with-cocoa", "with-modern-icon-elrumo1", "with-native-comp", "with-xwidgets"]
brew "koekeishiya/formulae/skhd"
brew "koekeishiya/formulae/yabai"
cask "aldente"
cask "arq"
cask "bartender", args: { appdir: "/Applications" }
cask "bob"
cask "clashx-pro"
cask "dash", args: { appdir: "/Applications" }
cask "dingtalk"
cask "discord"
cask "dropbox"
cask "firefox"
cask "font-hanamina"
cask "font-noto-sans-cjk"
cask "font-noto-serif-cjk"
cask "font-sf-mono"
cask "font-sf-pro"
cask "font-source-code-pro"
cask "iina", args: { appdir: "/Applications" }
cask "inkscape"
cask "iterm2"
cask "kap", args: { appdir: "/Applications" }
cask "karabiner-elements", args: { appdir: "/Applications" }
cask "keycastr"
cask "lark"
cask "launchbar", args: { appdir: "/Applications" }
cask "logitech-options"
cask "mactex-no-gui"
cask "maczip"
cask "microsoft-auto-update"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "miniconda"
cask "moneywiz", args: { appdir: "/Applications" }
cask "neteasemusic"
cask "omnidisksweeper", args: { appdir: "/Applications" }
cask "onedrive"
cask "skim", args: { appdir: "/Applications" }
cask "squirrel", args: { appdir: "/Applications" }
cask "syntax-highlight"
cask "telegram"
cask "tencent-meeting"
cask "thunder", args: { appdir: "/Applications" }
cask "wechattweak-cli"
cask "zoom"
mas "Bitwarden", id: 1352778147
mas "Grammarly for Safari", id: 1462114288
mas "Keynote", id: 409183694
mas "LanguageTool", id: 1534275760
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Peek", id: 1554235898
mas "QQ", id: 451108668
mas "Surfingkeys", id: 1599827286
mas "Take a Break", id: 1457158844
mas "Tampermonkey", id: 1482490089
mas "WeChat", id: 836500024
