#!/usr/bin/env sh

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# global settings
yabai -m config                                 \
    external_bar                 off:0:0        \
    menubar_opacity              1.0            \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    display_arrangement_order    default        \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_easing      ease_out_circ  \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.9            \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# space
yabai -m space 1 --label main
yabai -m space 2 --label submain
yabai -m space 3 --label misc

# rules
yabai -m rule --add app="Emacs" space=main
yabai -m rule --add app="Safari|Firefox" space=submain
yabai -m rule --add app="System Settings|System Information" manage=off sub-layer=below
yabai -m rule --add title="Copy|Bin|Info|Open" manage=off sub-layer=below
yabai -m rule --add app="LaunchBar|Bitwarden|Dash|Surge|Karabiner-Elements" manage=off sub-layer=below
yabai -m rule --add app="Messages|QQ|WeChat|Telegram|Music|Discord|Lark|Feishu|Slack|TencentMeeting|WeCom" space=misc manage=off sub-layer=below

# signals
chinese_app_regex="^QQ|WeChat|Telegram|Lark|Feishu$"
yabai -m signal --add event=application_activated app="$chinese_app_regex" action="fcitx-remote -s im.rime.inputmethod.Squirrel.Hans"
yabai -m signal --add event=application_activated app!="$chinese_app_regex" action="fcitx-remote -s com.apple.keylayout.US"

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

yabai -m signal --add event=window_created app="Karabiner-Elements" action='yabai -m window --focus $YABAI_WINDOW_ID'

float_script="if [ \$(yabai -m query --windows --window | jq '.\"can-resize\" == false and .\"is-floating\" == false') = 'true' ]; then
  yabai -m window --toggle float;
fi"
center_float_window="if [ \$(yabai -m query --windows --window | jq '.\"is-floating\" == true') == 'true' ]; then
  ~/.config/yabai/scripts/center-float-window.sh;
fi"
yabai -m signal --add event=window_created action="$float_script && $center_float_window"


echo "yabai configuration loaded.."
