#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_border                on
yabai -m config active_window_border_color   0xff61afef
yabai -m config normal_window_border_color   0xff555555
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_drop_action            stack

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                 12
yabai -m config right_padding                12
yabai -m config window_gap                   06

# space
yabai -m space 1 --label main
yabai -m space 2 --label submain
yabai -m space 3 --label misc

# rules
yabai -m rule --add app="Emacs" space=main
yabai -m rule --add app="Safari|Firefox" space=submain
yabai -m rule --add app="^System Preferences|System Information$" manage=off
yabai -m rule --add title="Copy|Bin|About This Mac|Info|Open" manage=off
yabai -m rule --add app="Bitwarden|Dash|Karabiner|Surge" manage=off
yabai -m rule --add app="QQ|WeChat|Telegram|Music|Lark|Feishu|Slack|TencentMeeting" manage=off space=misc

# signals
chinese_app_regex="^QQ|WeChat|Telegram|Lark|Feishu$"
yabai -m signal --add event=application_activated app="$chinese_app_regex" action="fcitx-remote -s im.rime.inputmethod.Squirrel.Rime"
yabai -m signal --add event=application_activated app!="$chinese_app_regex" action="fcitx-remote -s com.apple.keylayout.US"

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
