#!/usr/bin/env sh

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_shadow                on             \
    window_opacity_duration      0.0            \
    active_window_opacity        1.0            \
    normal_window_opacity        0.90           \
    window_opacity               off            \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 on             \
    top_padding                  12             \
    bottom_padding               12             \
    left_padding                 12             \
    right_padding                12             \
    window_gap                   06             \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap

# space
yabai -m space 1 --label main
yabai -m space 2 --label submain
yabai -m space 3 --label misc

# rules
yabai -m rule --add app="Emacs" space=main
yabai -m rule --add app="Safari|Firefox" space=submain
yabai -m rule --add app="^System Preferences|System Information$" manage=off
yabai -m rule --add title="Copy|Bin|About This Mac|Info|Open" manage=off
yabai -m rule --add app="Bitwarden|Dash|Karabiner|Surge|iTerm" manage=off
yabai -m rule --add app="QQ|WeChat|Telegram|Music|Discord|Lark|Feishu|Slack|TencentMeeting" manage=off space=misc

# signals
# chinese_app_regex="^QQ|WeChat|Telegram|Lark|Feishu$"
# yabai -m signal --add event=application_front_switched action="echo \$YABAI_PROCESS_ID \$YABAI_RECENT_PROCESS_ID"
# yabai -m signal --add event=application_front_switched action="fcitx-remote -s com.apple.keylayout.US"

yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
